# Minimal stub for Klipper's klippy/configfile.py -- only the members
# actually used by this project's extras/*.py, not the full real API.
from configparser import RawConfigParser
from typing import Any, List, Optional

from klippy import Printer

class error(Exception): ...

class ConfigWrapper:
    section: str
    fileconfig: RawConfigParser
    error: type[error]

    def __init__(self, printer: Printer, fileconfig: RawConfigParser,
                 access_tracking: dict, section: str) -> None: ...
    def get_printer(self) -> Printer: ...
    def get_name(self) -> str: ...
    def get(self, option: str, default: Any = ..., note_valid: bool = True) -> str: ...
    def getint(self, option: str, default: Any = ..., minval: Optional[int] = None,
               maxval: Optional[int] = None, note_valid: bool = True) -> int: ...
    def getfloat(self, option: str, default: Any = ..., minval: Optional[float] = None,
                 maxval: Optional[float] = None, above: Optional[float] = None,
                 below: Optional[float] = None, note_valid: bool = True) -> float: ...
    def getboolean(self, option: str, default: Any = ..., note_valid: bool = True) -> bool: ...
    def getlist(self, option: str, default: Any = ..., sep: str = ',',
                count: Optional[int] = None, note_valid: bool = True) -> List[str]: ...
    def getlists(self, option: str, default: Any = ..., seps: tuple = (',',),
                 count: Optional[int] = None, note_valid: bool = True) -> List[List[str]]: ...
    def getsection(self, section: str) -> ConfigWrapper: ...
    def has_section(self, section: str) -> bool: ...
    def deprecate(self, option: str, value: Any = None) -> None: ...
