# Minimal stub for Klipper's klippy/gcode.py -- only the members actually
# used by this project's extras/*.py.
from typing import Any, Callable, Optional

class CommandError(Exception): ...

class GCodeCommand:
    error: type[CommandError]
    respond_info: Callable[[str], None]
    respond_raw: Callable[[str], None]

    def get_command(self) -> str: ...
    def get_commandline(self) -> str: ...
    def get_command_parameters(self) -> dict: ...
    def get_raw_command_parameters(self) -> str: ...
    def ack(self, msg: Optional[str] = None) -> bool: ...
    def get(self, name: str, default: Any = ..., parser: Callable = str,
            minval: Any = None, maxval: Any = None, above: Any = None,
            below: Any = None) -> str: ...
    def get_int(self, name: str, default: Any = ..., minval: Optional[int] = None,
                maxval: Optional[int] = None) -> int: ...
    def get_float(self, name: str, default: Any = ..., minval: Optional[float] = None,
                  maxval: Optional[float] = None, above: Optional[float] = None,
                  below: Optional[float] = None) -> float: ...

class GCodeDispatch:
    ready_gcode_handlers: dict
    base_gcode_handlers: dict

    def register_command(self, cmd: str, func: Optional[Callable], when_not_ready: bool = False,
                          desc: Optional[str] = None) -> Optional[Callable]: ...
    def register_mux_command(self, cmd: str, key: str, value: Any, func: Callable,
                              desc: Optional[str] = None) -> None: ...
    def run_script_from_command(self, script: str) -> None: ...
    def run_script(self, script: str) -> None: ...
    def get_mutex(self) -> Any: ...
    def respond_info(self, msg: str, log: bool = True) -> None: ...
    def respond_raw(self, msg: str) -> None: ...
    def create_gcode_command(self, command: str, commandline: str, params: dict) -> GCodeCommand: ...
